name: Update README

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Replace placeholders in README
      run: |
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        REPO_LINK="https://github.com/$GITHUB_REPOSITORY"
        sed -i "s/{{REPOSITORY_NAME}}/$REPO_NAME/g" ./docs/README.md
        sed -i "s|{{REPOSITORY_LINK}}|$REPO_LINK|g" ./docs/README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add ./docs/README.md
        git commit -m 'Update README with repository name and link'
        git push

    - name: Output repository link
      run: |
        echo "Repository Link: https://github.com/$GITHUB_REPOSITORY"