name: Update README

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Replace placeholders in CONTRIBUTING
      run: |
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        REPO_LINK="https://github.com/$GITHUB_REPOSITORY/"
        sed -i "s/{{REPOSITORY_NAME}}/$REPO_NAME/g" ./docs/CONTRIBUTING.md
        sed -i "s|{{REPOSITORY_LINK}}/$REPO_LINK|g" ./docs/CONTRIBUTING.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add ./docs/CONTRIBUTING.md
        git commit -m 'Update CONTRIBUTING with repository name and link'
        git push